# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

include: ['_pages']
title: mikedanko.me
# subtitle: Person
name: Mike Danko
email: mike@l4m3.com
description: >- # this means to ignore newlines until "baseurl:"
  This is the website for Mike Danko, a software developer in the Columbus Ohio Area.
  I'm also a father, a radio amateur (KD8ORQ), and a musician.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mikedanko.me" # the base hostname & protocol for your site, e.g. http://example.com
repository: skord/kd8orqnet
# logo: "/assets/images/mines-danger.jpg"

author:
  name             : "Mike Danko"
  avatar           : "/assets/images/me.jpg"
  bio              : "This is the website for Mike Danko, a software developer in the Columbus Ohio Area. I'm also a father, a radio amateur (KD8ORQ), and a musician."
  location         : "Columbus, Ohio, USA"
  email            : "mike@l4m3.com"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      # url: "mailto:your.name@email.com"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      # url: "https://your-website.com"
    - label: "Mastodon"
      icon: "fab fa-fw fa-mastodon"
      url: "https://mastodon.social/@mikedanko"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/skord"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/mikedanko"
    - label: "Youtube"
      icon: "fab fa-fw fa-youtube"
      url: "https://www.youtube.com/mikedanko"
    - label: "Twitch"
      icon: "fab fa-fw fa-twitch"
      url: "https://www.twitch.tv/thumplexbumpitron"
    - label: "Soundcloud"
      icon: "fab fa-fw fa-soundcloud"
      url: "https://soundcloud.com/thumplexbumpitron"

footer:
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      # url: "https://your-website.com"
    - label: "Mastodon"
      icon: "fab fa-fw fa-mastodon"
      url: "https://mastodon.social/@mikedanko"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/skord"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/mikedanko"
    - label: "Youtube"
      icon: "fab fa-fw fa-youtube"
      url: "https://www.youtube.com/mikedanko"
    - label: "Soundcloud"
      icon: "fab fa-fw fa-soundcloud"
      url: "https://soundcloud.com/thumplexbumpitron"
    - label: "Twitch"
      icon: "fab fa-fw fa-twitch"
      url: "https://www.twitch.tv/thumplexbumpitron"

# Build settings
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: 'default'
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Collections
collections:
  recipes:
    output: true
    permalink: /:collection/:name/

whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# comments:
#   provider: "giscus"
#   giscus:
#     repo_id: "R_kgDOJH90gA"
#     category_name: "General"
#     category_id: "DIC_kwDOJH90gM4CUycM"
#     discussion_term: "pathname"
#     reactions_enabled: 1
#     theme: "preferred_color_scheme"

category_archive:
  type: jekyll-archives
  path: /categories/
tag_archive:
  type: jekyll-archives
  path: /tags/

exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor/
  - vendor/bundle/
  - .vendor/
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - bin/
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gemfile.lock
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - .do/

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

compress_html:
  clippings: all
  ignore:
    envs: development

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: false
      share: true
      related: true
      show_date: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false
      comments: false
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: false
      share: true
      comments: false
  # _recipes
  - scope:
      path: ""
      type: recipes
    values:
      layout: single
      author_profile: false
      share: true
      comments: false


jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive-taxonomy
    tag: archive-taxonomy
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/
