name: kd8orqnet
static_sites:
- name: jekyll-site
  environment_slug: jekyll
  source_dir: /
  output_dir: public
  build_command: bundle exec jekyll build -d ./public
  index_document: index.html
  error_document: 404.html
  github:
    repo: skord/kd8orqnet
    branch: main
    deploy_on_push: true